-- 코드를 입력하세요
SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, TO_CHAR(R.CREATED_DATE, 'yyyy-mm-dd') AS CREATED_DATE
FROM USED_GOODS_BOARD B, USED_GOODS_REPLY R
WHERE TO_CHAR(B.CREATED_DATE, 'YY-MM') = '22-10' AND B.BOARD_ID = R.BOARD_ID
ORDER BY CREATED_DATE, TITLE